# Generated by Django 6.1 on 2026-09-07 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEmpresa', models.CharField(max_length=100)),
                ('logo1', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('logo2', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='proyecto/logo/')),
                ('descripcion', models.TextField(blank=True)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('estado', models.CharField(max_length=50)),
                ('brochure', models.FileField(blank=True, null=True, upload_to='proyecto/brochure/')),
                ('viewBox', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='proyectos.empresa')),
            ],
        ),
    ]
