# Generated by Django 6.1 on 2026-09-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='moneda',
        ),
    ]
