# Generated by Django 6.1 on 2026-09-07 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.PositiveIntegerField()),
                ('porcentaje', models.PositiveSmallIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['anio', 'mes'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroContacto', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('whatsappLink', models.URLField(blank=True)),
                ('imagecontacto', models.ImageField(blank=True, null=True, upload_to='proyecto/contacto/')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='proyecto/equipo/')),
                ('descripcion', models.TextField(blank=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='HeroStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop', models.FileField(upload_to='proyecto/hero/')),
                ('imagenHero', models.ImageField(blank=True, null=True, upload_to='proyecto/hero/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('button', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_stages', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ImageAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyecto/avances/')),
                ('avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='contenido.avance')),
            ],
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nosotros', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ImageNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proyecto/nosotros/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('nosotros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='contenido.nosotros')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('imageUbicacion', models.ImageField(blank=True, null=True, upload_to='proyecto/ubicacion/')),
                ('linkUbicacion', models.URLField(blank=True)),
                ('iframeUbicacion', models.TextField(blank=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='proyectos.proyecto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='avance',
            constraint=models.UniqueConstraint(fields=('proyecto', 'mes', 'anio'), name='avance_unico_por_mes'),
        ),
    ]
