import floorImage from "./planoVertice.png";
import departmentsSvg from "./departments.svg";
import departmentPaths from "../aurora/departmentPaths";

const project = {
    id: 2,
    slug: "vertice",
    nombre: "Vertice Tower",
    ciudad: "Santa Cruz",
    direccion: "Equipetrol",
    descripcion:
        "Proyecto residencial con diseño contemporáneo y excelente ubicación.",
    precioDesde: 120000,
    moneda: "USD",
    estado: "En Venta",
    hero: {
        image: floorImage,
        video: null,
    },
    logo: null,
    planos: {
        floorImage,
        departmentsSvg,
        departmentPaths,
    },
    pisos: [
        {
            id: 1,
            numero: 1,
            nombre: "PISO 1",
            colorFondo: "#d9c2a3",
            departamentos: [
                {
                    id: "B101",
                    codigo: "B101",
                    estado: "Disponible",
                    precio: 125000,
                    moneda: "USD",
                    superficie: 88,
                    dormitorios: 3,
                    banos: 2,
                    render3D: null,
                    planoTecnico: null,
                    galeria: [],
                    tour360: null,
                },
                {
                    id: "B102",
                    codigo: "B102",
                    estado: "Reservado",
                    precio: 128000,
                    moneda: "USD",
                    superficie: 91,
                    dormitorios: 3,
                    banos: 2,
                    render3D: null,
                    planoTecnico: null,
                    galeria: [],
                    tour360: null,
                },
                {
                    id: "B103",
                    codigo: "B103",
                    estado: "Disponible",
                    precio: 125000,
                    moneda: "USD",
                    superficie: 88,
                    dormitorios: 3,
                    banos: 2,
                    render3D: null,
                    planoTecnico: null,
                    galeria: [],
                    tour360: null,
                },
                {
                    id: "B104",
                    codigo: "B104",
                    estado: "Reservado",
                    precio: 128000,
                    moneda: "USD",
                    superficie: 91,
                    dormitorios: 3,
                    banos: 2,
                    render3D: null,
                    planoTecnico: null,
                    galeria: [],
                    tour360: null,
                },
                {
                    id: "B105",
                    codigo: "B105",
                    estado: "Disponible",
                    precio: 125000,
                    moneda: "USD",
                    superficie: 88,
                    dormitorios: 3,
                    banos: 2,
                    render3D: null,
                    planoTecnico: null,
                    galeria: [],
                    tour360: null,
                },
                {
                    id: "B106",
                    codigo: "B106",
                    estado: "Reservado",
                    precio: 128000,
                    moneda: "USD",
                    superficie: 91,
                    dormitorios: 3,
                    banos: 2,
                    render3D: null,
                    planoTecnico: null,
                    galeria: [],
                    tour360: null,
                },
                {
                    id: "B107",
                    codigo: "B107",
                    estado: "Disponible",
                    precio: 125000,
                    moneda: "USD",
                    superficie: 88,
                    dormitorios: 3,
                    banos: 2,
                    render3D: null,
                    planoTecnico: null,
                    galeria: [],
                    tour360: null,
                },
                {
                    id: "B108",
                    codigo: "B108",
                    estado: "Reservado",
                    precio: 128000,
                    moneda: "USD",
                    superficie: 91,
                    dormitorios: 3,
                    banos: 2,
                    render3D: null,
                    planoTecnico: null,
                    galeria: [],
                    tour360: null,
                },
            ],
        },

    ],

};

export default project;