import renderA101 from "./departaments/A101/render3D.png";
import planoA101 from "./departaments/A101/PlanoTecnico.png";
import fotoA101_1 from "./departaments/A101/galeria/foto1.png";
import fotoA101_2 from "./departaments/A101/galeria/foto2.png";
import fotoA101_3 from "./departaments/A101/galeria/foto3.png";
import fotoA101_4 from "./departaments/A101/galeria/foto4.png";
import fotoA101_5 from "./departaments/A101/galeria/foto5.png";
import floorImage from "./planoAurora.png";
import departmentsSvg from "./departments.svg";
import departmentPaths from "./departmentPaths";
import frameA101 from "./departaments/A101/frameA101.png";

const project = {
    id: 1,
    slug: "aurora",
    nombre: "Edificio Aurora",
    ciudad: "La Paz",
    direccion: "Av. Costanera",
    descripcion:
        "Departamentos modernos con excelente ubicación, áreas comunes y acabados de alta calidad.",
    precioDesde: 95000,
    moneda: "USD",
    estado: "En Venta",
    hero: {
        image: fotoA101_1,
        video: null,
    },
    logo: null,
    planos: {
        floorImage,
        departmentsSvg,
        departmentPaths,
        departmentMap: {
        left: "15.65%",
        top: "18.1%",
        width: "69.9%",
        viewBox: "0 0 2670 1350",
    },
    },
    pisos: [
        {
            id: 1,
            numero: 1,
            nombre: "PISO 1",
            colorFondo: "#24baab",
            departamentos: [
                {
                    id: "A101",
                    codigo: "A101",
                    tipo: "Monoambiente",
                    estado: "Disponible",
                    precio: 120000,
                    moneda: "USD",
                    superficie: 85,
                    dormitorios: 3,
                    banos: 2,
                    cocina: 1,
                    render3D: renderA101,
                    planoTecnico: planoA101,
                    galeria: [
                        fotoA101_1,
                        fotoA101_2,
                        fotoA101_3,
                        fotoA101_4,
                        fotoA101_5,
                    ],
                    frame: frameA101,
                    tour360: "https://kuula.co/share/5VXwm?logo=1&info=1&fs=1&vr=0&sd=1&thumbs=1",
                },
                {
                    id: "A102",
                    codigo: "A102",
                    estado: "Reservado",
                    precio: 118000,
                    moneda: "USD",
                    superficie: 82,
                    dormitorios: 3,
                    banos: 2,
                },
                {
                    id: "A103",
                    codigo: "A103",
                    estado: "Vendido",
                    precio: 115000,
                    moneda: "USD",
                    superficie: 80,
                    dormitorios: 2,
                    banos: 2,
                },
                {
                    id: "A104",
                    codigo: "A104",
                    estado: "Disponible",
                    precio: 118000,
                    moneda: "USD",
                    superficie: 82,
                    dormitorios: 3,
                    banos: 2,
                },
                {
                    id: "A105",
                    codigo: "A105",
                    estado: "Disponible",
                    precio: 115000,
                    moneda: "USD",
                    superficie: 80,
                    dormitorios: 2,
                    banos: 2,
                },
                {
                    id: "A106",
                    codigo: "A106",
                    estado: "Disponible",
                    precio: 120000,
                    moneda: "USD",
                    superficie: 85,
                    dormitorios: 3,
                    banos: 2,
                    render3D: renderA101,
                    planoTecnico: planoA101,
                    galeria: [
                        fotoA101_1,
                        fotoA101_2,
                        fotoA101_3,
                        fotoA101_4,
                        fotoA101_5,
                    ],
                    tour360: null,
                },
                {
                    id: "A107",
                    codigo: "A107",
                    estado: "Reservado",
                    precio: 118000,
                    moneda: "USD",
                    superficie: 82,
                    dormitorios: 3,
                    banos: 2,
                },
                {
                    id: "A108",
                    codigo: "A108",
                    estado: "Vendido",
                    precio: 115000,
                    moneda: "USD",
                    superficie: 80,
                    dormitorios: 2,
                    banos: 2,
                },
                {
                    id: "A109",
                    codigo: "A109",
                    estado: "Disponible",
                    precio: 118000,
                    moneda: "USD",
                    superficie: 82,
                    dormitorios: 3,
                    banos: 2,
                },
                {
                    id: "A110",
                    codigo: "A110",
                    estado: "Disponible",
                    precio: 115000,
                    moneda: "USD",
                    superficie: 80,
                    dormitorios: 2,
                    banos: 2,
                },
            ],
        },
        {
            id: 2,
            numero: 2,
            nombre: "PISO 2",
            colorFondo: "#D8E27C",
            departamentos: [
                {
                    id: "A201",
                    codigo: "A201",
                    estado: "Disponible",
                    precio: 125000,
                    moneda: "USD",
                    superficie: 90,
                    dormitorios: 3,
                    banos: 2,
                },
                {
                    id: "A202",
                    codigo: "A202",
                    estado: "Disponible",
                    precio: 128000,
                    moneda: "USD",
                    superficie: 92,
                    dormitorios: 3,
                    banos: 2,
                },
            ],
        },
        {
            id: 3,
            numero: 3,
            nombre: "PISO 3",
            colorFondo: "#243ddd",
            departamentos: [
                {
                    id: "A301",
                    codigo: "A301",
                    estado: "Disponible",
                    precio: 130000,
                    moneda: "USD",
                    superficie: 95,
                    dormitorios: 3,
                    banos: 2,
                },
                {
                    id: "A302",
                    codigo: "A302",
                    estado: "Disponible",
                    precio: 132000,
                    moneda: "USD",
                    superficie: 97,
                    dormitorios: 3,
                    banos: 2,
                },
            ],
        },
    ],
};

export default project;