# Generated by Django 6.1 on 2026-09-07 21:07

import django.core.validators
import django.db.models.deletion
import recorrido.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombrePiso', models.CharField(max_length=100)),
                ('imagePiso', models.ImageField(upload_to=recorrido.models.piso_image_path)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pisos', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dormitorios', models.PositiveIntegerField(blank=True, null=True)),
                ('banos', models.PositiveIntegerField(blank=True, null=True)),
                ('sala', models.PositiveIntegerField(blank=True, null=True)),
                ('lavanderia', models.PositiveIntegerField(blank=True, null=True)),
                ('cocina', models.PositiveIntegerField(blank=True, null=True)),
                ('comedor', models.PositiveIntegerField(blank=True, null=True)),
                ('render3D', models.ImageField(blank=True, null=True, upload_to=recorrido.models.unidad_render_path)),
                ('planoTecnico', models.ImageField(blank=True, null=True, upload_to=recorrido.models.unidad_plano_path)),
                ('frame', models.ImageField(blank=True, null=True, upload_to=recorrido.models.unidad_frame_path)),
                ('tour360', models.URLField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_unidad', to='recorrido.categoriaunidad')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_unidad', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTipoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=recorrido.models.unidad_galeria_path)),
                ('tipoUnidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='recorrido.tipounidad')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'Vendido ')], default=1)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.PositiveSmallIntegerField(choices=[(1, '$US'), (2, 'BOB')])),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='recorrido.piso')),
                ('tipoUnidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='recorrido.tipounidad')),
            ],
            options={
                'permissions': [('cambiar_estado_unidad', 'Puede cambiar estado de unidad'), ('ver_historial_unidad', 'Puede ver historial de unidades')],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecioUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='recorrido.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstadoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'Vendido ')])),
                ('estado_nuevo', models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'Vendido ')])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='recorrido.unidad')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tipounidad',
            constraint=models.UniqueConstraint(fields=('proyecto', 'codigo'), name='unique_codigo_tipo_unidad_proyecto'),
        ),
    ]
