# Generated by Django 6.1 on 2026-09-10 14:21

import recorrido.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipounidad',
            name='fichaTecnica',
            field=models.ImageField(blank=True, null=True, upload_to=recorrido.models.tipo_unidad_ficha_path),
        ),
    ]
